const defaultPrefs={calories:2000,protein:90,fiber:30,theme:'light',eggs:true,dairy:true,avoid:'',lang:'en-IN',rate:1,voice:'',autoSpeak:false};
let prefs={...defaultPrefs,...S.prefs};
const dairyIds=['milk','yogurt','curd_tadka','mango_lassi','milk_coffee','tea','ghee'];
function allFoods(){return [...F,...S.cus.filter(x=>Number.isFinite(x.k)&&Number.isFinite(x.p)).map(x=>({id:x.id,name:x.n,unit:'g',d:100,base:100,kcal:x.k,p:x.p,c:0,f:0,fiber:0,buffer:1,cat:'custom',photo:x.photo,custom:true}))]}
S.cus.forEach(x=>{if(!x.id)x.id='custom_'+crypto.randomUUID()});save();
function photoKey(id){return ({wheat_dosa:'dosa',rava_idli:'idli',spinach_sambar:'sambar',radish_sambar:'sambar',black_chana_sambar:'chana',veg_curry:'curry',curd_tadka:'yogurt',mango_lassi:'lassi',black_coffee:'coffee',milk_coffee:'coffee',roasted_chana:'roasted_chana'})[id]||id}
function picture(id,name,customPhoto){const photo=customPhoto||PHOTOS[photoKey(id)]?.src;return `<div class="pic"><span class="photo-fallback">${esc(name)}</span>${photo?`<img src="${esc(photo)}" alt="${esc(name)} — illustrative food photo" loading="lazy" onerror="this.hidden=true">`:''}</div>`}
function drawFoods(){const q=(document.getElementById('foodSearch')?.value||'').trim().toLowerCase();let a=allFoods().filter(x=>(cat==='all'||x.cat===cat)&&x.name.toLowerCase().includes(q)&& (prefs.eggs||x.id!=='egg')&&(prefs.dairy||!dairyIds.includes(x.id)));document.getElementById('foods').innerHTML=a.map(x=>{let selected=S.sel[x.id],amount=selected?selected.a:x.d;return `<article class="food ${selected?'on':''}"><button class="food-select" aria-pressed="${!!selected}" aria-label="${selected?'Remove':'Add'} ${esc(x.name)}" onclick="toggle(event,'${x.id}')">${picture(x.id,x.name,x.photo).replace('</div>',`<span class="pick" aria-hidden="true">${selected?'✓':'+'}</span></div>`)}<div class="food-info"><b>${esc(x.name)}</b><small>${x.d} ${x.unit} · ~${Math.round(x.kcal*x.d/x.base*x.buffer)} kcal</small></div></button>${selected?`<div class="ctrl"><button class="step" aria-label="Decrease ${esc(x.name)}" onclick="changeAmount('${x.id}',-1)">−</button><input aria-label="${esc(x.name)} portion" type="number" min="0" max="10000" step="${x.unit==='g'||x.unit==='ml'?5:0.5}" value="${amount}" oninput="amt('${x.id}',Math.max(0,Math.min(10000,+this.value)))"><small>${x.unit}</small><button class="step" aria-label="Increase ${esc(x.name)}" onclick="changeAmount('${x.id}',1)">+</button></div>`:''}</article>`}).join('')||'<p class="note">No matching foods. Add a grocery in Settings.</p>'}
function changeAmount(id,dir){let f=food(id),step=['g','ml'].includes(f.unit)?25:0.5;amt(id,Math.max(0,(S.sel[id]?.a||0)+dir*step));drawFoods()}
function tot(){let t=T();document.getElementById('kcal').textContent=Math.round(t.k);document.getElementById('pro').textContent=t.p.toFixed(1)+' g';document.getElementById('fib').textContent=t.fi.toFixed(1)+' g';document.getElementById('kcalTarget').textContent=`of ${prefs.calories} kcal`;document.getElementById('proteinTarget').textContent=`of ${prefs.protein} g protein`;document.getElementById('fiberTarget').textContent=`of ${prefs.fiber} g fiber`;for(const [id,value,max] of [['kcal',t.k,prefs.calories],['protein',t.p,prefs.protein],['fiber',t.fi,prefs.fiber]]){const el=document.getElementById(id+'Progress');el.max=max;el.value=value}carb.textContent=`Carbs ${t.c.toFixed(1)} g`;fat.textContent=`Fat ${t.f.toFixed(1)} g`;if(Object.keys(S.sel).some(id=>food(id)?.custom)){carb.textContent+=' + untracked custom food';fat.textContent+=' + untracked custom food'}}
function eligibleRecipes(){return R.filter(r=>(prefs.eggs||!r.ingredients.includes('egg'))&&(prefs.dairy||!r.ingredients.some(id=>dairyIds.includes(id))))}
function drawRecipes(){recipesList.innerHTML=R.filter(r=>(prefs.eggs||!r.ingredients.includes('egg'))&&(prefs.dairy||!r.ingredients.some(id=>dairyIds.includes(id)))).map(r=>{let n=rn(r),id=r.ingredients.find(id=>!['rice','egg','salad','yogurt','ghee'].includes(id))||r.ingredients[0];return `<article class="recipe">${picture(id,r.name)}<div class="recipe-body"><h3>${r.name}</h3><small>${r.time} · ~${Math.round(n.k)} kcal · ${n.p.toFixed(0)} g protein</small><br><button class="btn alt" onclick="loadR('${r.id}')">Add to plate</button><details><summary>Ingredients & steps</summary><div class="steps">${r.ingredients.map(id=>food(id).name).join(', ')}<ol>${r.steps.map(s=>`<li>${s}</li>`).join('')}</ol></div></details></div></article>`}).join('')||'<p class="note">No matching preset recipes. Ask Coach for a meal using your food preferences.</p>'}
function drawCustom(){custom.innerHTML=S.cus.map(x=>`<div class="row"><span><b>${esc(x.n)}</b><br>${x.k??'Unknown'} kcal · ${x.p??'Unknown'} g protein /100 g</span><button class="textbtn" aria-label="Remove ${esc(x.n)}" onclick="removeCustom('${x.id}')">Remove</button></div>`).join('');customPantry.innerHTML=S.cus.map(x=>`<label class="pi"><input type="checkbox" ${S.pan[x.id]!==false?'checked':''} onchange="S.pan['${x.id}']=this.checked;save()"><span>${esc(x.n)}</span></label>`).join('')}
let undoAction,toastTimer;function toast(text,undo){const el=document.getElementById('toast');undoAction=undo;el.innerHTML=esc(text)+(undo?'<button onclick="undoAction();this.parentElement.hidden=true">Undo</button>':'');el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,10000)}
function resetPlate(){let prior=structuredClone(S.sel);S.sel={};save();drawFoods();tot();toast('Plate cleared',()=>{S.sel=prior;save();drawFoods();tot()})}
function removeCustom(id){const prior=structuredClone({cus:S.cus,sel:S.sel,pan:S.pan});S.cus=S.cus.filter(x=>x.id!==id);delete S.sel[id];delete S.pan[id];save();drawCustom();drawFoods();tot();toast('Grocery removed',()=>{Object.assign(S,prior);save();drawCustom();drawFoods();tot()})}
function drawChat(){chat.innerHTML=S.chat.length?S.chat.slice(-60).map(m=>`<div class="msg ${m.r==='u'?'u':'b'}">${esc(m.t||'Thinking…')}</div>`).join(''):'<div class="chat-welcome"><div class="eyebrow">LET’S MAKE FOOD EASY</div><h3>What sounds good today?</h3><p class="note">Ask for a meal, an ingredient swap,<br>or a simple plan for a busy day.</p></div>';chat.scrollTop=chat.scrollHeight}
function ask(question){q.value=question;send()}
function clearConversation(){if(document.getElementById('sendCoach').disabled){toast('Wait until the current reply finishes.');return}const prior=structuredClone(S.chat);S.chat=[];last='Tell me what you feel like eating.';save();drawChat();toast('Conversation cleared',()=>{S.chat=prior;save();drawChat()})}
function speak(){if(!window.speechSynthesis)return toast('Speech is unavailable in this browser.');let u=new SpeechSynthesisUtterance(last);u.lang=prefs.lang;u.rate=prefs.rate;u.voice=speechSynthesis.getVoices().find(v=>v.voiceURI===prefs.voice)||null;speechSynthesis.cancel();speechSynthesis.speak(u)}
function populateVoices(){let select=document.getElementById('prefVoice');select.innerHTML='<option value="">Device default</option>'+ (window.speechSynthesis?.getVoices()||[]).map(v=>`<option value="${esc(v.voiceURI)}">${esc(v.name)} (${esc(v.lang)})</option>`).join('');select.value=prefs.voice}
function applyPrefs(){document.body.classList.toggle('dark',prefs.theme==='dark');for(const [id,key] of [['Calories','calories'],['Protein','protein'],['Fiber','fiber'],['Theme','theme'],['Avoid','avoid'],['Lang','lang'],['Rate','rate']])document.getElementById('pref'+id).value=prefs[key];for(const [id,key] of [['Eggs','eggs'],['Dairy','dairy'],['AutoSpeak','autoSpeak']])document.getElementById('pref'+id).checked=prefs[key];populateVoices();tot();drawFoods();drawRecipes()}
document.getElementById('preferences').onsubmit=e=>{e.preventDefault();prefs={calories:+prefCalories.value,protein:+prefProtein.value,fiber:+prefFiber.value,theme:prefTheme.value,eggs:prefEggs.checked,dairy:prefDairy.checked,avoid:prefAvoid.value.trim(),lang:prefLang.value,rate:+prefRate.value,voice:prefVoice.value,autoSpeak:prefAutoSpeak.checked};S.prefs=prefs;save();applyPrefs();document.getElementById('prefsStatus').textContent='Preferences saved.';toast('Preferences saved')};
async function photoFromFile(file){if(!file)return undefined;if(!file.type.startsWith('image/')||file.size>10000000)throw Error('Choose an image under 10 MB.');const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');const scale=Math.min(1,640/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/jpeg',0.75)}
document.getElementById('groceryForm').onsubmit=async e=>{e.preventDefault();const status=document.getElementById('groceryStatus');try{let n=cn.value.trim();if(!n)return;const photo=await photoFromFile(customPhoto.files[0]);let item={id:'custom_'+crypto.randomUUID(),n,k:ck.value===''?null:+ck.value,p:cp.value===''?null:+cp.value,photo};S.cus.unshift(item);S.pan[item.id]=true;try{save()}catch(err){S.cus.shift();delete S.pan[item.id];throw Error('Phone storage is full. Try a grocery without a photo.')}e.target.reset();drawCustom();drawFoods();status.textContent='Grocery added to your pantry.';toast('Grocery added')}catch(err){status.textContent=err.message}};
function exportData(){const blob=new Blob([JSON.stringify({app:'HarshaFuel',version:5,data:S},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='harsha-fuel-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Backup download started')}
document.getElementById('restoreData').onchange=async e=>{try{let file=e.target.files[0];if(!file)return;if(file.size>4000000)throw Error('Backup must be under 4 MB.');let backup=JSON.parse(await file.text());if(backup.app!=='HarshaFuel'||!backup.data)throw Error('Choose a Harsha Fuel backup.');const d=backup.data;if(!Array.isArray(d.cus)||!Array.isArray(d.chat)||!d.sel||typeof d.sel!=='object'||!d.pan||typeof d.pan!=='object')throw Error('Invalid backup data.');if(d.cus.length>200||d.chat.length>2000)throw Error('Backup is too large.');if(d.cus.some(x=>typeof x.n!=='string'||x.n.length>60||!/^custom_[a-zA-Z0-9-]+$/.test(x.id)|| (x.photo&&!/^data:image\/jpeg;base64,[a-zA-Z0-9+/=]+$/.test(x.photo)) || (x.k!==null&&(!Number.isFinite(x.k)||x.k<0||x.k>1000))||(x.p!==null&&(!Number.isFinite(x.p)||x.p<0||x.p>100))))throw Error('Invalid grocery data.');if(d.chat.some(x=>!['u','b'].includes(x.r)||typeof x.t!=='string'))throw Error('Invalid chat data.');const ids=new Set([...F.map(x=>x.id),...d.cus.map(x=>x.id)]);for(const [id,v] of Object.entries(d.sel))if(!ids.has(id)||!Number.isFinite(v.a)||v.a<0||v.a>10000)throw Error('Invalid meal data.');if(d.prefs){const p=d.prefs;if(!Number.isFinite(p.calories)||p.calories<1||p.calories>10000||!Number.isFinite(p.protein)||p.protein<1||p.protein>500||!Number.isFinite(p.fiber)||p.fiber<1||p.fiber>100||!['light','dark'].includes(p.theme)||typeof p.avoid!=='string'||p.avoid.length>250)throw Error('Invalid preferences.')}if(!confirm('Replace your current meals, pantry, preferences and chat with this backup? Your saved Gemma model stays in place.'))return;const prior=S;S={sel:d.sel,pan:d.pan,cus:d.cus,chat:d.chat,prefs:d.prefs};try{save()}catch(err){S=prior;throw err}prefs={...defaultPrefs,...S.prefs};applyPrefs();drawPan();drawChat();toast('Backup restored')}catch(err){toast(err.message||'Could not restore backup')}finally{e.target.value=''}};
if(window.speechSynthesis)speechSynthesis.onvoiceschanged=populateVoices;
cats.push(['custom','My groceries']);drawCats();drawPan();drawChat();applyPrefs();
document.getElementById('photoCredits').innerHTML=Object.values(PHOTOS).map(p=>`<p><a href="${esc(p.page)}" target="_blank" rel="noopener noreferrer">${esc(p.title)}</a> — ${esc(p.credit)} · <a href="${esc(p.licenseUrl)}" target="_blank" rel="noopener noreferrer">${esc(p.license)}</a> · resized/cropped</p>`).join('');
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
